### ISSUE TITLE
Week 08 - Day 2 - # Spit and Polish

### ISSUE THREAD

**Issue by mdewey** [onemira/Official-Assignments#28]
# Spit and Polish

Your GitHub repository will be part of your portfolio and you will likely link to it from your portfolio.

Creating a clean looking README is as important for a project as having nice clean code.

Here are some examples of great READMEs:

- https://github.com/axios/axios
- https://github.com/Microsoft/vscode
- https://github.com/twbs/bootstrap
- https://github.com/electron/electron

Here are some example of great student READMEs:

- https://github.com/cfsanderson/Minesweeper
- https://github.com/m1g/tic-react-toe
- https://github.com/m1g/snowman

## Objectives

- Create quality readmes

### Explorer Mode

- [x] Work on any outstanding homework assignments, focusing on assignments, not so much capstone. 
- [x] Choose several (at least three) repositories to update the READMEs
- [x] Include a description, in your own words, of what the assignment was
- [x] Include a list of technologies (and links to the homepage for each) you used
- [x] Include a link to the project in production (surge, etc.)
- [x] Include a screenshot or an animated gif (see [Kap](https://github.com/wulkano/kap), [Recordit](http://recordit.co/), or [Licecap](https://www.cockos.com/licecap/))
- Optional:
  - [ ] Include an aspect you are particularly proud of
  - [ ] Include a snippet of code you are proud of (see GitHub Markdown on how to format code snippets)

**Comment by onemira** [comment]
1. https://github.com/onemira/colorpicker-hooked
2. https://github.com/onemira/minesweeper
3. https://github.com/Elro1118/moviehouse

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBVZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--978506c32fc72f81eabd7234e584cda7e38900af/giphy-6.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/71)**__
