### ISSUE TITLE
Week 03 - day 1 - Catch your Breath

### ISSUE THREAD

**Issue by mdewey** [onemira/Official-Assignments#9]
# Catch your Breath

We have been going at a fast pace for the past couple of weeks. Every so often, you need to reflect on how far you have come.

In this assignment, we are going to take a little _code_ break and create a blog post. Writing is a good way to reflect on what you have done and also share some knowledge. The best way to get better at talking about technology is practice. Blog posts are a way to practice that skill.

## Objectives

- Practice talking about technology
- Reinforce a topic we have covered in class

## Requirements

- Create a blog on [Medium](https://medium.com/).

### Explorer Mode

- [x] On [Medium](https://medium.com/), create a blog post that talks about a concept we have gone over in class. This could anything topic from HTML, CSS or JavaScript, or a "lesson learned" from the past couple of weeks. As a challenge, consider picking a topic you think you are weak on. Remember, you are creating a developer-focused blog post.
- [x] Solve this kata: [https://www.codewars.com/kata/volume-of-a-cuboid](https://www.codewars.com/kata/volume-of-a-cuboid) To turn this in, create a [gist](https://gist.github.com) of your code and submit a link to it.
- [x] Submit the link to your published blog post when turning in this assignment.

## Adventure Mode

- [ ] continue to work on blackjack
- [ ] As we progress, we will be using different tools to work our brain. Today, head over to [HackerRank](https://www.hackerrank.com/). This is another tool, like [Codewars](https://www.codewars.com/) to practice our developer skills. As a start, head into the algorithms section, and try [Grading Students](https://www.hackerrank.com/challenges/grading/problem).
- [ ] To turn this in, create a [gist](https://gist.github.com) of your code and submit a link to it.

### Epic Mode

- [ ] Go back and finish up any outstanding work.
- [ ] Go back to a previous assignment and work on it some more. This could be trying to tackle a harder level, working on the UI/UX, refactoring the code to a new idea that we covered (e.g. functions and abstractions), or adding unit tests.
- [ ] To turn this in, link to the other project's repository, and describe what you did.

**Comment by onemira** [comment]
https://gist.github.com/onemira/0feb4f2e77922ff73ece8044e7a72f1a

https://medium.com/@mirabulgogi/i-am-a-2-week-old-developer-b8e3ffd4e9ea
:) ENJOYED CATCHING-A-BREATH MOMENT! 
READY TO RUN AGAIN! 👍

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBUZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--395b5be9a8246c8cf018274388a5d5392825ae8e/giphy-2.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/67)**__
